//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.1
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exprodtoolbox.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("exprodtoolbox.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на http://errorreporting.ufssp44.ru:81/q.php?report={0}.
        /// </summary>
        internal static string ErrorReportURL {
            get {
                return ResourceManager.GetString("ErrorReportURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select MON$USER, MON$REMOTE_ADDRESS, MON$REMOTE_PROCESS, MON$TIMESTAMP from MON$ATTACHMENTS.
        /// </summary>
        internal static string FBMon {
            get {
                return ResourceManager.GetString("FBMon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select count(*) from MON$ATTACHMENTS.
        /// </summary>
        internal static string FBMonCnt {
            get {
                return ResourceManager.GetString("FBMonCnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PK	Идентификатор записи
        ///NPP	Порядковый номер ИП
        ///NUM_IP	Номер ИП
        ///DATE_IP_IN	Дата возбуждения ИП
        ///DATE_TOW_MONTHS	Дата исполнения
        ///DATE_DONE_SELF	Дата для добровольного исполнения
        ///OVIP	Признак контроля ОВИП
        ///DATE_OVIP_IN	Дата постановки на контроль
        ///FIO_OVIP_KONTROL	ФИО лица осуществляющего контроль
        ///OVIP_KONTROL_TYPE	Категория контроля
        ///DATE_SVOD_IN	Дата присоединения ИП к сводному
        ///PK_SVOD	Ссылка на сводное ИП
        ///SOLID_NUM	Количество ИП в составе сводного
        ///RESULT	Результат исполнения
        ///REASON_OUT	Причина о [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string fields {
            get {
                return ResourceManager.GetString("fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на update IP set IP.MAIN_D=NULL where (IP.SSD is not null)and(IP.SSV is not null)and(IP.MAIN_D = 1) .
        /// </summary>
        internal static string fix18 {
            get {
                return ResourceManager.GetString("fix18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select count(IP1.NUM_IP) from IP IP1 where (IP1.SSD is not null)and(IP1.SSV is not null)and(IP1.MAIN_D = 1).
        /// </summary>
        internal static string fix18if {
            get {
                return ResourceManager.GetString("fix18if", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на update IP_IN_SUM set FK_VID_PLAT = null where VID_SUM &lt;&gt; &apos;долг взыскателю&apos; and FK_VID_PLAT is not null.
        /// </summary>
        internal static string fix20 {
            get {
                return ResourceManager.GetString("fix20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select count(IP1.NUM_IP) from IP IP1,IP_IN_SUM S where (S.FK=IP1.PK)and(S.VID_SUM&lt;&gt;&apos;долг взыскателю&apos;)and(S.FK_VID_PLAT is not null).
        /// </summary>
        internal static string fix20if {
            get {
                return ResourceManager.GetString("fix20if", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на update IP set ip.sum_=0 where (IP.SISP_KEY in (&quot;/1/3/&quot;,&quot;/1/48/&quot;,&quot;/1/49/&quot;,&quot;/1/52/&quot;)) and (IP.SUM_ &gt; 0).
        /// </summary>
        internal static string fix22 {
            get {
                return ResourceManager.GetString("fix22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select count(IP1.NUM_IP) from IP IP1 where (IP1.SISP_KEY in (&quot;/1/3/&quot;,&quot;/1/48/&quot;,&quot;/1/49/&quot;,&quot;/1/52/&quot;)) and (IP1.SUM_ &gt; 0).
        /// </summary>
        internal static string fix22if {
            get {
                return ResourceManager.GetString("fix22if", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на update s_subdividings
        ///set path_doc=&apos;{1}&apos;,
        ///templates_path=&apos;{2}&apos;.
        /// </summary>
        internal static string fixdox {
            get {
                return ResourceManager.GetString("fixdox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ALTER TABLE S_USERS ADD IBE$$TEMP_COLUMN
        /// INTEGER DEFAULT 0;
        ///UPDATE RDB$RELATION_FIELDS F1
        ///SET
        ///F1.RDB$DEFAULT_VALUE  = (SELECT F2.RDB$DEFAULT_VALUE
        ///                         FROM RDB$RELATION_FIELDS F2
        ///                         WHERE (F2.RDB$RELATION_NAME = &apos;S_USERS&apos;) AND
        ///                               (F2.RDB$FIELD_NAME = &apos;IBE$$TEMP_COLUMN&apos;)),
        ///F1.RDB$DEFAULT_SOURCE = (SELECT F3.RDB$DEFAULT_SOURCE FROM RDB$RELATION_FIELDS F3
        ///                         WHERE (F3.RDB$RELATION_NAME = &apos;S_USERS&apos;) AND
        ///      [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string fixnewuser {
            get {
                return ResourceManager.GetString("fixnewuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на update s_users set s_users.kind_of_office=1.
        /// </summary>
        internal static string fixoo {
            get {
                return ResourceManager.GetString("fixoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на update s_users set s_users.uspassword=&apos;{0}&apos;.
        /// </summary>
        internal static string fixpassword {
            get {
                return ResourceManager.GetString("fixpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select count(*) from ip where  ((vidd_KEY like &apos;/1/5%&apos;) or (vidd_key like &apos;/2/%&apos;))and (IP.DATE_IP_OUT is null)and(IP.SSD is null)and(IP.SSV is null).
        /// </summary>
        internal static string toSiteCnt {
            get {
                return ResourceManager.GetString("toSiteCnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select ip.NAME_D,ip.VIDD_TTL,ip.ADR_D,ip.NAME_ORG_ID, id.d_id, id.num_id, s_subdividings.sd from ip left join id on ip.pk_id=id.pk,S_SUBDIVIDINGS where ((ip.vidd_KEY like &apos;/1/5%&apos;) or (ip.vidd_key like &apos;/2/%&apos;))and (IP.DATE_IP_OUT is null)and(IP.SSD is null)and(IP.SSV is null).
        /// </summary>
        internal static string toSiteQuery {
            get {
                return ResourceManager.GetString("toSiteQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на http://dl.dropbox.com/u/4987235/up379/deposit379.zip.
        /// </summary>
        internal static string UpdDeposit3_7_9url {
            get {
                return ResourceManager.GetString("UpdDeposit3_7_9url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на http://dl.dropbox.com/u/4987235/up379/Ex_prod_server3_07_9.zip.
        /// </summary>
        internal static string UpdEx_prod_server3_07_9url {
            get {
                return ResourceManager.GetString("UpdEx_prod_server3_07_9url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на http://dl.dropbox.com/u/4987235/up379/Ex_Prod_templates3_07_9.zip.
        /// </summary>
        internal static string UpdTemplates3_7_9url {
            get {
                return ResourceManager.GetString("UpdTemplates3_7_9url", resourceCulture);
            }
        }
    }
}
